import { useState } from 'react';
import { X } from 'lucide-react';
import { useApp } from '../context/AppContext';
import type { TicketPriority } from '../types';
export default function CreateTicketModal({ onClose }: { onClose: () => void }) {
  const { addTicket, categories, agents, currentAgent } = useApp(); const [subject,setSubject]=useState(''); const [description,setDescription]=useState(''); const [email,setEmail]=useState(''); const [name,setName]=useState(''); const [priority,setPriority]=useState<TicketPriority>('medium'); const [categoryId,setCategoryId]=useState(''); const [assignedTo,setAssignedTo]=useState(''); const [saving,setSaving]=useState(false); const [error,setError]=useState<string | null>(null);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError(null);try{await addTicket({subject,description,priority,categoryId:categoryId||undefined,assignedTo:assignedTo||undefined,createdBy:email,customerName:name||undefined});onClose();}catch(err){setError(err instanceof Error?err.message:'Could not create ticket');}finally{setSaving(false);}};
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white shadow-2xl"><header className="sticky top-0 flex items-center justify-between border-b bg-white px-6 py-4"><h2 className="text-xl font-semibold">Create ticket</h2><button type="button" onClick={onClose} className="rounded p-2 hover:bg-gray-100"><X size={20}/></button></header><div className="space-y-4 p-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Customer email *<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required className="mt-1 w-full rounded-lg border px-3 py-2" placeholder="customer@example.com"/></label><label className="text-sm font-medium">Customer name<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2" placeholder="Optional"/></label></div><label className="block text-sm font-medium">Subject *<input value={subject} onChange={e=>setSubject(e.target.value)} minLength={3} required className="mt-1 w-full rounded-lg border px-3 py-2"/></label><label className="block text-sm font-medium">Description *<textarea value={description} onChange={e=>setDescription(e.target.value)} minLength={10} required rows={6} className="mt-1 w-full rounded-lg border px-3 py-2"/></label><div className="grid gap-4 sm:grid-cols-3"><label className="text-sm font-medium">Priority<select value={priority} onChange={e=>setPriority(e.target.value as TicketPriority)} className="mt-1 w-full rounded-lg border px-3 py-2"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label className="text-sm font-medium">Category<select value={categoryId} onChange={e=>setCategoryId(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"><option value="">None</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm font-medium">Assign<select value={assignedTo} onChange={e=>setAssignedTo(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"><option value="">Unassigned</option>{agents.filter(a=>a.isActive).map(a=><option key={a.id} value={a.id}>{a.fullName}</option>)}</select></label></div>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<p className="text-xs text-gray-500">Created by signed-in agent: {currentAgent?.fullName}</p></div><footer className="flex gap-3 border-t px-6 py-4"><button type="button" onClick={onClose} className="flex-1 rounded-lg border px-4 py-2">Cancel</button><button disabled={saving} className="flex-1 rounded-lg bg-blue-600 px-4 py-2 text-white disabled:opacity-60">{saving?'Creating…':'Create ticket'}</button></footer></form></div>;
}
