import { useMemo, useState } from 'react';
import { Plus, Search, Filter, Bot } from 'lucide-react';
import { useApp } from '../context/AppContext';
import type { Ticket, TicketPriority, TicketStatus } from '../types';
import CreateTicketModal from './CreateTicketModal';
import TicketDetailModal from './TicketDetailModal';

const badge = (status: string) => status === 'open' ? 'bg-red-100 text-red-700' : status === 'in_progress' ? 'bg-yellow-100 text-yellow-700' : status === 'resolved' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-700';
const slaBadge = (sla?: string) => sla === 'green' ? 'bg-green-100 text-green-700' : sla === 'warning' ? 'bg-yellow-100 text-yellow-700' : sla === 'breached' ? 'bg-red-100 text-red-700' : 'bg-gray-100 text-gray-400';
const slaLabel = (sla?: string) => sla ? sla.charAt(0).toUpperCase() + sla.slice(1) : '—';
export default function TicketList() {
  const { tickets, loading } = useApp();
  const [search, setSearch] = useState(''); const [status, setStatus] = useState<TicketStatus | 'all'>('all'); const [priority, setPriority] = useState<TicketPriority | 'all'>('all');
  const [createOpen, setCreateOpen] = useState(false); const [selected, setSelected] = useState<Ticket | null>(null);
  const filtered = useMemo(() => tickets.filter(t => (t.subject + t.description + t.ticketNumber).toLowerCase().includes(search.toLowerCase()) && (status === 'all' || t.status === status) && (priority === 'all' || t.priority === priority)), [tickets, search, status, priority]);
  return <><div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tickets…" className="w-full rounded-lg border border-gray-300 py-2 pl-10 pr-4 focus:border-blue-500 focus:ring-2 focus:ring-blue-500"/></div><button onClick={()=>setCreateOpen(true)} className="flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-white hover:bg-blue-700"><Plus size={20}/>New Ticket</button></div>
    <div className="flex flex-wrap gap-3"><div className="flex items-center gap-2"><Filter size={16} className="text-gray-500"/><select value={status} onChange={e=>setStatus(e.target.value as TicketStatus | 'all')} className="rounded-lg border border-gray-300 px-3 py-1.5 text-sm"><option value="all">All status</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting_for_customer">Waiting for customer</option><option value="waiting_for_internal">Waiting for internal</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></div><select value={priority} onChange={e=>setPriority(e.target.value as TicketPriority | 'all')} className="rounded-lg border border-gray-300 px-3 py-1.5 text-sm"><option value="all">All priority</option><option value="urgent">Urgent</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div>
    <div className="overflow-hidden rounded-lg border border-gray-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[840px]"><thead className="border-b bg-gray-50"><tr className="text-left text-xs font-medium uppercase text-gray-500"><th className="px-6 py-3">Ticket</th><th className="px-6 py-3">Subject</th><th className="px-6 py-3">Status</th><th className="px-6 py-3">Priority</th><th className="px-6 py-3">SLA</th><th className="px-6 py-3">Category</th><th className="px-6 py-3">Assigned</th><th className="px-6 py-3">Created</th></tr></thead><tbody className="divide-y">{filtered.map(t=><tr key={t.id} onClick={()=>setSelected(t)} className="cursor-pointer hover:bg-blue-50/50"><td className="px-6 py-4 font-mono text-sm">{t.ticketNumber}</td><td className="px-6 py-4"><p className="max-w-xs truncate font-medium text-gray-900">{t.subject}</p>{t.summary && <p className="mt-1 flex max-w-xs items-center gap-1 truncate text-xs text-gray-500"><Bot size={13} className="text-blue-500"/>{t.summary}</p>}</td><td className="px-6 py-4"><span className={`rounded-full px-2 py-1 text-xs font-medium ${badge(t.status)}`}>{t.status.replace(/_/g, ' ')}</span></td><td className="px-6 py-4"><span className="capitalize text-sm text-gray-700">{t.priority}</span></td><td className="px-6 py-4"><span className={`rounded-full px-2 py-1 text-xs font-medium ${slaBadge(t.slaStatus)}`}>{slaLabel(t.slaStatus)}</span>{t.slaDueAt && <p className="mt-1 text-[10px] text-gray-400">{new Date(t.slaDueAt).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric' })}</p>}</td><td className="px-6 py-4">{t.category ? <span style={{backgroundColor:t.category.color}} className="rounded-full px-2 py-1 text-xs text-white">{t.category.name}</span> : <span className="text-sm text-gray-400">None</span>}</td><td className="px-6 py-4 text-sm">{t.assignedAgent?.fullName || 'Unassigned'}</td><td className="px-6 py-4 text-sm text-gray-500">{new Date(t.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>{loading ? <p className="p-8 text-center text-sm text-gray-500">Loading live tickets…</p> : filtered.length === 0 ? <p className="p-10 text-center text-sm text-gray-500">No tickets match these filters.</p> : null}</div></div>{createOpen && <CreateTicketModal onClose={()=>setCreateOpen(false)}/>} {selected && <TicketDetailModal ticket={selected} onClose={()=>setSelected(null)}/>}</>;
}
